import { Lead, OutreachDraft, IcpConfig, PipelineMetrics } from "@/types/dashboard";

export const initialIcpConfig: IcpConfig = {
  id: "icp_default",
  targetIndustries: ["B2B SaaS", "FinTech", "HealthTech", "Cybersecurity", "Cloud Infrastructure"],
  minEmployees: 50,
  maxEmployees: 500,
  targetLocations: ["United States", "Canada", "United Kingdom", "Western Europe"],
  requiredTechStack: ["AWS", "Salesforce", "React"],
  preferredTechStack: ["PostgreSQL", "HubSpot", "Docker", "Snowflake"],
  negativeKeywords: ["Staffing Agency", "Cryptocurrency Trading", "Student Project"],
  minQualificationScore: 75,
  autoEnrichThreshold: 80,
  autoDraftOutreach: true,
  updatedAt: new Date().toISOString(),
};

export const initialLeads: Lead[] = [
  {
    id: "lead_001",
    companyName: "Summit Digital Health",
    website: "https://summitdigital.io",
    industry: "HealthTech & SaaS",
    employeeCount: 140,
    location: "Boston, MA, USA",
    contactName: "Marcus Vance",
    contactTitle: "VP of Sales & Revenue Operations",
    contactEmail: "marcus.v@summitdigital.io",
    contactLinkedin: "https://linkedin.com/in/marcus-vance-sales",
    stage: "outreach_ready",
    score: 96,
    confidence: 94,
    scoreBreakdown: {
      industryMatch: 98,
      companySize: 95,
      techStack: 94,
      intentSignals: 97,
      overallScore: 96,
    },
    technologies: ["AWS", "Salesforce", "React", "Docker", "HubSpot"],
    intentSignals: [
      "Hiring 4 Outbound Account Executives (posted 3d ago)",
      "Announced $14M Series A Funding (TechCrunch)",
      "Recently migrated CRM to Salesforce Enterprise",
    ],
    auditLogs: [
      {
        id: "log_1",
        step: "research",
        agentName: "Research Agent (Tavily/Playwright)",
        reasoning: "Located domain summitdigital.io. Crawled /careers and /about. Detected B2B HIPAA-compliant workflow engine.",
        confidence: 95,
        citations: ["https://summitdigital.io/about", "https://techcrunch.com/2026/summit-funding"],
        timestamp: "10 mins ago",
      },
      {
        id: "log_2",
        step: "qualification",
        agentName: "Qualification Agent (JSON Schema)",
        reasoning: "Matches ICP: Verticals HealthTech + B2B SaaS. Employee headcount 140 fits [50-500] band. Located in Boston, MA.",
        confidence: 98,
        citations: ["LinkedIn company insights"],
        timestamp: "8 mins ago",
      },
      {
        id: "log_3",
        step: "enrichment",
        agentName: "Enrichment Agent (Hunter/Clearbit)",
        reasoning: "Found VP of Sales Marcus Vance with verified MX deliverability score 99%. Validated SMTP handshakes.",
        confidence: 96,
        citations: ["hunter.io/verify", "mx1.summitdigital.io"],
        timestamp: "5 mins ago",
      },
      {
        id: "log_4",
        step: "scoring",
        agentName: "Scoring Agent (Hybrid LLM)",
        reasoning: "High buying intent confirmed by 4 active sales hires and recent capital injection. Total score evaluated to 96/100.",
        confidence: 94,
        timestamp: "3 mins ago",
      },
    ],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lead_002",
    companyName: "CloudScale Analytics",
    website: "https://cloudscale.ai",
    industry: "Cloud Infrastructure",
    employeeCount: 220,
    location: "San Francisco, CA, USA",
    contactName: "Elena Rostova",
    contactTitle: "Head of Growth & Demand Gen",
    contactEmail: "elena@cloudscale.ai",
    contactLinkedin: "https://linkedin.com/in/elena-rostova",
    stage: "outreach_ready",
    score: 92,
    confidence: 91,
    scoreBreakdown: {
      industryMatch: 94,
      companySize: 92,
      techStack: 96,
      intentSignals: 86,
      overallScore: 92,
    },
    technologies: ["AWS", "React", "PostgreSQL", "Snowflake", "Kubernetes"],
    intentSignals: [
      "Visited Pricing page 3 times in last 48 hours",
      "Expanding SDR team by 35% in Q3",
    ],
    auditLogs: [
      {
        id: "log_21",
        step: "research",
        agentName: "Research Agent",
        reasoning: "Discovered CloudScale through G2 category scraping. Identified SaaS data warehousing tool.",
        confidence: 92,
        citations: ["https://cloudscale.ai"],
        timestamp: "24 mins ago",
      },
      {
        id: "log_22",
        step: "qualification",
        agentName: "Qualification Agent",
        reasoning: "Verified 220 employees on LinkedIn. Headquartered in SF. AWS and Snowflake confirmed.",
        confidence: 94,
        timestamp: "20 mins ago",
      },
      {
        id: "log_23",
        step: "enrichment",
        agentName: "Enrichment Agent",
        reasoning: "Enriched decision maker Elena Rostova. Verified direct business email.",
        confidence: 90,
        timestamp: "15 mins ago",
      },
    ],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lead_003",
    companyName: "FinPulse Labs",
    website: "https://finpulse.co",
    industry: "FinTech",
    employeeCount: 85,
    location: "Toronto, Canada",
    contactName: "David Sterling",
    contactTitle: "Chief Revenue Officer",
    contactEmail: "d.sterling@finpulse.co",
    stage: "enriched",
    score: 88,
    confidence: 89,
    scoreBreakdown: {
      industryMatch: 90,
      companySize: 88,
      techStack: 85,
      intentSignals: 89,
      overallScore: 88,
    },
    technologies: ["AWS", "Salesforce", "Node.js", "Stripe"],
    intentSignals: ["New Series B announcement", "Hiring Product Marketing Lead"],
    auditLogs: [
      {
        id: "log_31",
        step: "research",
        agentName: "Research Agent",
        reasoning: "Discovered through Crunchbase Series B feed.",
        confidence: 90,
        timestamp: "45 mins ago",
      },
    ],
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lead_004",
    companyName: "CyberShield Security",
    website: "https://cybershield.net",
    industry: "Cybersecurity",
    employeeCount: 310,
    location: "Austin, TX, USA",
    contactName: "Rachel Kim",
    contactTitle: "Director of Inbound & Outbound Sales",
    contactEmail: "rkim@cybershield.net",
    stage: "qualified",
    score: 84,
    confidence: 86,
    scoreBreakdown: {
      industryMatch: 88,
      companySize: 85,
      techStack: 82,
      intentSignals: 81,
      overallScore: 84,
    },
    technologies: ["AWS", "React", "HubSpot"],
    intentSignals: ["Expanding US sales territory"],
    auditLogs: [
      {
        id: "log_41",
        step: "research",
        agentName: "Research Agent",
        reasoning: "Crawled security vendor index. Verified active commercial product.",
        confidence: 88,
        timestamp: "1 hour ago",
      },
    ],
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "lead_005",
    companyName: "RetailBoost AI",
    website: "https://retailboost.org",
    industry: "E-Commerce Tech",
    employeeCount: 18,
    location: "Miami, FL, USA",
    contactName: "Alex Rivera",
    contactTitle: "Founder & CEO",
    contactEmail: "alex@retailboost.org",
    stage: "disqualified",
    score: 42,
    confidence: 95,
    scoreBreakdown: {
      industryMatch: 60,
      companySize: 20,
      techStack: 50,
      intentSignals: 38,
      overallScore: 42,
    },
    technologies: ["Shopify", "WordPress"],
    intentSignals: ["No recent hiring activity"],
    auditLogs: [
      {
        id: "log_51",
        step: "qualification",
        agentName: "Qualification Agent",
        reasoning: "Disqualified: Headcount is 18 (below minimum required threshold of 50). Missing required tech stack (AWS/Salesforce).",
        confidence: 96,
        citations: ["https://linkedin.com/company/retailboost"],
        timestamp: "2 hours ago",
      },
    ],
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialOutreachDrafts: OutreachDraft[] = [
  {
    id: "draft_001",
    leadId: "lead_001",
    companyName: "Summit Digital Health",
    contactName: "Marcus Vance",
    contactEmail: "marcus.v@summitdigital.io",
    contactTitle: "VP of Sales & Revenue Operations",
    channel: "email",
    subject: "Scaling outbound for Summit Digital's 4 new AEs?",
    body: `Hi Marcus,

Saw that Summit Digital recently closed your $14M Series A and you're actively scaling out 4 new Account Executive roles in Boston — huge congrats on the momentum!

As your new reps ramp up, keeping their calendars filled with qualified healthcare SaaS buyers is usually the biggest bottleneck. We built Leadwise to autonomously research tech stacks, verify HIPAA compliance triggers, and populate reps' pipelines with verified decision-makers.

Would you be open to a 10-minute chat this Thursday at 2:00 PM EST to see how we could help your incoming AEs hit quota faster?

Best regards,
Alex | Sales Strategy @ Leadwise`,
    personalizedHook: "Referenced their $14M Series A funding and 4 active AE job postings.",
    signalsCited: [
      "Series A $14M Funding announcement",
      "4 Outbound AE job requisitions on Careers page",
      "Recent Salesforce CRM deployment",
    ],
    status: "pending_approval",
    generatedAt: "12 mins ago",
  },
  {
    id: "draft_002",
    leadId: "lead_002",
    companyName: "CloudScale Analytics",
    contactName: "Elena Rostova",
    contactEmail: "elena@cloudscale.ai",
    contactTitle: "Head of Growth & Demand Gen",
    channel: "email",
    subject: "Question regarding CloudScale's Q3 SDR expansion",
    body: `Hi Elena,

Noticed CloudScale's rapid expansion and your upcoming 35% growth across the outbound SDR team this quarter.

Given your focus on enterprise data analytics, manual prospecting on LinkedIn usually costs your reps 15+ hours each week. Leadwise deploys autonomous AI agents that identify enterprise teams querying data warehouses and routes them directly into your CRM.

Open to seeing a quick 3-minute personalized sample lead list for CloudScale?

Best,
Jordan | Growth Partnerships`,
    personalizedHook: "Referenced their 35% SDR expansion and high pricing page engagement.",
    signalsCited: [
      "35% team headcount growth signal",
      "Repeat pricing page visits detected",
    ],
    status: "pending_approval",
    generatedAt: "25 mins ago",
  },
];

export const initialMetrics: PipelineMetrics = {
  leadsPerHour: 48,
  qualificationRate: 78.4,
  totalLeadsDiscovered: 1248,
  totalQualified: 978,
  totalEnriched: 842,
  totalOutreachPending: 24,
  activeAgentRuns: 4,
  throughputHistory: [
    { hour: "08:00", discovered: 32, qualified: 24 },
    { hour: "09:00", discovered: 45, qualified: 36 },
    { hour: "10:00", discovered: 58, qualified: 44 },
    { hour: "11:00", discovered: 52, qualified: 41 },
    { hour: "12:00", discovered: 40, qualified: 31 },
    { hour: "13:00", discovered: 48, qualified: 39 },
    { hour: "14:00", discovered: 62, qualified: 49 },
    { hour: "15:00", discovered: 55, qualified: 43 },
  ],
  stageDistribution: [
    { stage: "discovered", label: "Discovered", count: 270, color: "#94A3B8" },
    { stage: "researching", label: "Researching", count: 85, color: "#38BDF8" },
    { stage: "qualified", label: "Qualified", count: 420, color: "#2DD4BF" },
    { stage: "enriched", label: "Enriched", count: 310, color: "#3B82F6" },
    { stage: "outreach_ready", label: "Outreach Ready", count: 112, color: "#FF5A36" },
    { stage: "contacted", label: "Contacted", count: 51, color: "#10B981" },
  ],
  recentActivity: [
    {
      id: "act_1",
      type: "outreach_generated",
      title: "Outreach draft generated for Marcus Vance (Summit Digital)",
      description: "Cited Series A funding and 4 AE job openings. Confidence score 94%.",
      time: "10 mins ago",
    },
    {
      id: "act_2",
      type: "lead_qualified",
      title: "CloudScale Analytics qualified with 92% score",
      description: "220 employees in SF, AWS and Snowflake stack verified.",
      time: "24 mins ago",
    },
    {
      id: "act_3",
      type: "lead_discovered",
      title: "Batch of 14 new candidate domains ingested",
      description: "Source: Crunchbase Series A feed for B2B SaaS.",
      time: "38 mins ago",
    },
    {
      id: "act_4",
      type: "agent_alert",
      title: "Enrichment Agent verified 28 emails with 0 bounces",
      description: "SMTP handshake passed for all newly staged contacts.",
      time: "1 hour ago",
    },
  ],
};
